apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sportbook-prod-appset
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                #- name: sportsbook-cashout-engine
                - name: sportsbook-bet-api
                #- name: sportsbook-resulting-api
                # - name: sportsbook-bet-validation-api
                # - name: resulting-jackpots-engine-java
                # - name: sportsbook-bet-builder-api
                # - name: sportsbook-bet-builder-consumers
                # - name: sportsbook-bet-cashout-api
                # - name: resulting-lost-bets-engine-java
                # - name: resulting-won-bets-engine-java
                # - name: sportsbook-award-jp-bonus-api
                # - name: sportsbook-cancel-mts-bet-consumer
          - list:
              elements:
                - env: betika-ug #betika_ug
                  server: https://kubernetes.default.svc
                - env: betika-tz
                  server: https://kubernetes.default.svc
                # - env: betika_cd
                #   server: https://kubernetes.default.svc

    # Specific applications for certain environments
    # - matrix:
    #     generators:
    #       - list:
    #           elements:
    #             - name: betengine-reserve-api
    #       - list:
    #           elements:
    #             - env: betika_ke
    #             - env: betika_cd

    # - matrix:
    #     generators:
    #       - list:
    #           elements:
    #             - name: cashout-mts-publisher
    #       - list:
    #           elements:
    #             - env: betika_cd

  template:
    metadata:
      name: "{{name}}-{{env}}"
    spec:
      project: sportsbook-production
      source:
        repoURL: "https://github.com/BetikaDevOps/sportsbook-argocd-apps.git"
        targetRevision: HEAD
        path: helm-chart/sportsbook
        helm:
          valueFiles:
            - values/{{env}}/{{name}}.yaml
      destination:
        server:  "{{server}}" #https://kubernetes.default.svc
        namespace: "{{env}}"
      syncPolicy:
        automated: {}  # No auto-sync
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true  