apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sportbook-devel-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: sportsbook-cashout-engine
          - name: sportsbook-bet-api
          - name: sportsbook-resulting-api
          #- name: sportsbook-bet-validation-api
          #- name: resulting-jackpots-engine-java
  template:
    metadata:
      name: "{{name}}-devel"
    spec:
      project: sportsbook-devel
      source:
        repoURL: "https://github.com/BetikaDevOps/sportsbook-argocd-apps.git"
        targetRevision: HEAD
        path: sportsbook-team/sportsbook-chart
        helm:
          valueFiles:
            - ../sportsbook-chart/values/devel/{{name}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: devel
      syncPolicy:
        automated:
          prune: true
          selfHeal: true