
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Values.service.name }}
#   namespace: {{ .Values.namespace }}
#   labels:
#     {{- include "sportsbook.labels" . | nindent 4 }}
# spec:
#   selector:
#     app: {{ .Values.appName }}
#   type: {{ .Values.service.type }} 
#   ports:
#     - name: http
#       port: {{ .Values.service.port }}
#       targetPort: {{ .Values.service.targetPort }}
#       protocol: TCP


{{- if .Values.service.http.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.http.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sportsbook.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.service.http.type }}
  ports:
    - name: http
      port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
      protocol: TCP
{{- end }}

{{- if .Values.service.grpc.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.grpc.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sportsbook.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.service.grpc.type }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpc.port }}
      targetPort: {{ .Values.service.grpc.targetPort }}
      protocol: TCP
{{- end }}

