{{- if .Values.service.http.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sportsbook.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.service.type }} 
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      
{{- end }}



