apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sportsbook.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.envVars }}
  {{ $key }}: "{{ $value }}"
  {{- end }}